import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { Provider } from 'react-redux'
import { store } from '@/redux/store'
import { useSelector , useDispatch } from 'react-redux';
import { useEffect } from 'react'
import axios from 'axios'
import { setCurrent_user } from '@/redux/userSlice'


export default function App({ Component, pageProps }: AppProps) {
  console.log("render")

  return (
    <>
      <Head>
        <title>BlogtorNext</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <Component {...pageProps} />
      </Provider>
    </>
  )
}
